class AppImages{
 static const  String whiteCarrot= "assets/images/whiteCarrot.png";
 static const  String man = "assets/images/man.png";
 static const  String carrot = "assets/images/carrot.png";
 static const  String vegetables = "assets/images/vegetables.png";
 static const  String banana = "assets/images/banana.png";
 static const  String apple = "assets/images/Apple.png";
 static const  String redPepper = "assets/images/red pepper.png";
 static const  String ginger = "assets/images/ginger.png";
 static const  String rice = "assets/images/rice.png";
 static const  String pulses = "assets/images/pulses.png";
 static const  String beefBone = "assets/images/beef bone.png";
 static const  String broilerChicken = "assets/images/broiler chicken.png";
 static const  String freshFruits = "assets/images/Frash Fruits.png";
 static const  String cookingOil = "assets/images/Cooking Oil.png";
 static const  String meetFish = "assets/images/meetAndfish.png";
 static const  String bakerySnackes = "assets/images/Bakery & Snacks.png";
 static const  String DairyEggs = "assets/images/Dairy & Eggs.png";
 static const  String Beverages = "assets/images/Beverages.png";
 static const  String eggs = "assets/images/eggs.png";
 static const  String sprite_can = "assets/images/Sprite Can.png";
 static const  String Diet_coke = "assets/images/Diet Coke.png";
 static const  String Apple_juice = "assets/images/Apple & Grape Juice.png";
 static const  String coca_cola = "assets/images/Coca Cola Can.png";
 static const  String pepsi_can  = "assets/images/Pepsi Can.png";
 static const  String userImage  = "assets/images/userImage.png";
 static const  String pament  = "assets/images/pament.png";
 static const  String orederAccepted  = "assets/images/orderAccepted.png";
}